name: "units-test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: today
      uses: ./
